/** Semantic color tokens matching CSS custom properties in main.css */
export const COLORS = {
  bg: "var(--c-bg)",
  surface: "var(--c-surface)",
  "surface-raised": "var(--c-surface-raised)",
  "border-grid": "var(--c-border-grid)",
  "border-grid-faint": "var(--c-border-grid-faint)",
  border: "var(--c-border)",
  hex: "var(--c-hex)",
  muted: "var(--c-muted)",
  label: "var(--c-label)",
  text: "var(--c-text)",
  "text-bright": "var(--c-text-bright)",
  accent: "var(--c-accent)",
  success: "var(--c-success)",
  cyan: "var(--c-cyan)",
  purple: "var(--c-purple)",
  danger: "var(--c-danger)",
  "danger-light": "var(--c-danger-light)",
  "accent-bg": "var(--c-accent-bg)",
  "accent-bg-hover": "var(--c-accent-bg-hover)",
  "accent-bg-subtle": "var(--c-accent-bg-subtle)",
  "danger-bg": "var(--c-danger-bg)",
  "danger-bg-subtle": "var(--c-danger-bg-subtle)",
  "danger-border": "var(--c-danger-border)",
} as const;
